<?php

namespace AppBundle\Repository;

/**
 * ElectricResultsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElectricResultsRepository extends \Doctrine\ORM\EntityRepository
{
}
